zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181"
kafka:
  build: .
  ports:
    - "9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'neverwinter,random1,random2,random3'
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    